spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/smartutility
    username: postgres
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

cds:
  data-source:
    auto-config:
      enabled: false
  outbox:
    services:
      DefaultOutboxOrdered:
        enabled: false
      DefaultOutboxUnordered:
        enabled: false
    enabled: false
jwt:
    secret: "smart-utility-management-secret-key"
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000

